import "./globals.css";
import { Inter } from "next/font/google";
import Breadcrumb from "@/components/BreadCrumb";
import Login from "@/components/Login";
import Logout from "@/components/Logout";
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log("AUTH OPTIONS: " + authOptions);
  console.log(authOptions);
  console.log("SESSION: " + session);

  if (session) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <div>
            <Breadcrumb />
            <div className="mx-10 mt-8">{children}</div>
          </div>
        </body>
      </html>
    );
  }
  else {
    return (
      <html lang="en">
        <body className={inter.className}>
          <div className="max-w-3xl mx-auto p-4">
            <div>
              <br></br>
              <Login />
              <br></br>
            </div>
          </div>
        </body>
      </html>
    )
  }
}